linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - typecheck
    # Replacing deprecated linters
    - revive  # replacement for golint

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/takutakahashi/claude-posts

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m
  tests: true
